USE `io-db`;

INSERT INTO students VALUES(20182020095, 'Jose Andrés', 'Sanabria Arias', 'joasanabriaa@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20181020066, 'Kevin Duván', 'Bernal Ortiz', 'kdbernalo@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20181020064, 'Jonathan Steven', 'Cruz Monroy', 'joscruzm@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020065, 'Juan Camilo', 'Cespedes Romero', 'jccespedesr@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020084, 'Jackson', 'Luna Bonilla', 'jlunab@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020080, 'William Enrique', 'Forero Neira', 'weforeron@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020008, 'Diego Fernando', 'Román López', 'dfromanl@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020109, 'Josué Daniel', 'Rodríguez Siatama', 'jodrodriguezs@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020133, 'Ibzan Jared', 'Peralta Rosero', 'ijperaltar@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020113, 'Andrés Felipe', 'Barbosa Cárdenas', 'anfbarbosac@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020043, 'David Steven', 'Saldarriaga Pardo', 'dssaldarriagap@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020082, 'Juan David', 'Hurtado Peñaloza', 'judhurtadop@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020094, 'Santiago', 'Herrera Velásquez', 'sherrerav@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020018, 'Juan Camilo', 'Herrera Gómez', 'jucherrerag@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020151, 'Brayan Steven', 'Arellano Espinosa', 'bsarellanoe@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20161150007, 'Hanna Caroline', 'Villamil Ortiz', 'hcvillamilo@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20152020222, 'Dannyr Gustavo', 'García Cardozo', 'dggarcia@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20172020110, 'Maria Fernanda', 'Uribe Hernández', 'mfuribeh@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020015, 'Reinaldo', 'Espinel Torres', 'respinelt@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020013, 'Daniel Julián', 'Vargas Jaime', 'djvargasj@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020003, 'Jonathan Estiven', 'Castellanos Castellanos', 'joecastellanosc@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020056, 'Andrés Felipe', 'Morera Díaz', 'aforerad@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020039, 'Juan Sebastian', 'Angulo Cita', 'jsanguloc@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020133, 'Nicolas', 'Pérez Sánchez', 'nperezs@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020161, 'Jhonatan Steven', 'Vega Novoa', 'jsvegan@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020127, 'Samuel Andrés', 'Romero Bueno', 'saromerob@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020117, 'Jhon Sebastian', 'Alberto Cortes', 'jsalbertoc@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20192020010, 'Jonathan Estiven', 'Martínez Malaver', 'joemartinezm@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20172020060, 'Jorge Alberto', 'Galeano Vélez', 'jagaleanov@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20181020089, 'Juan Camilo', 'Ramírez Rátiva', 'jcramirezr@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20191020058, 'Yuneider', 'Parada Pérez', 'yparadap@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20182020125, 'Andrés Felipe', 'Gutierrez Ramírez', 'andfgutierrezr@correo.udistrital.edu.co', 'Ingeniería de Sistemas');
INSERT INTO students VALUES(20181020068, 'Johan Daniel', 'Cortés Garcia', 'jdcortesg@correo.udistrital.edu.co', 'Ingeniería de Sistemas');